# Generated by Django 2.2.5 on 2019-10-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='paginas')),
                ('texto', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.CharField(default='x', max_length=4),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='x', max_length=120),
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='x', max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default='x', max_length=120),
        ),
        migrations.AddField(
            model_name='pagina',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
    ]
