# Generated by Django 2.2.5 on 2019-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20191026_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='numero',
            field=models.IntegerField(editable=False),
        ),
    ]
