# Generated by Django 2.2.5 on 2019-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20191026_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='texto',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
